---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hooks.captainhook.io
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "captain-hook.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  group: captainhook.io
  names:
    kind: Hook
    listKind: HookList
    plural: hooks
    shortNames:
      - hook
    singular: hook
  scope: Namespaced
  version: v1alpha1
