---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hooks.captainhook.io
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "captain-hook.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  group: captainhook.io
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      # Schema
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                forwardURL:
                  type: string
                body:
                  type: string
                headers:
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: string
            status:
              type: object
              properties:
                status:
                  type: string
                attempts:
                  type: integer
                message:
                  type: string
                noRetryBefore:
                  type: date
                completedTimestamp:
                  type: date
      additionalPrinterColumns:
        - name: ForwardURL
          type: string
          jsonPath: .spec.forwardURL
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    kind: Hook
    listKind: HookList
    plural: hooks
    shortNames:
      - hook
    singular: hook
