---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hooks.captainhook.io
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "captain-hook.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  group: captainhook.io
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      # Schema
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                forwardURL:
                  type: string
                body:
                  type: string
                headers:
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: string
            status:
              type: object
              properties:
                status:
                  type: string
                attempts:
                  type: integer
                message:
                  type: string
                noRetryBefore:
                  type: string
                completedTimestamp:
                  type: string
      additionalPrinterColumns:
        - name: Forward URL
          type: string
          jsonPath: .spec.forwardURL
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Attempts
          type: integer
          description: The number of attempts the webhooks has had.
          jsonPath: .status.attempts
          priority: 1
        - name: No Retry Before
          type: date
          description: Do not attempt to retry this webhook before.
          jsonPath: .status.noRetryBefore
          priority: 1
          format: date-time
        - name: Completed
          type: date
          description: When this hook was successfully sent.
          jsonPath: .status.completedTimestamp
          priority: 1
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Error
          type: string
          jsonPath: .status.message
          priority: 1
  scope: Namespaced
  names:
    kind: Hook
    listKind: HookList
    plural: hooks
    shortNames:
      - hook
    singular: hook
