{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "captain-hook.serviceAccountName" . }}
  labels:
    {{- include "captain-hook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "captain-hook.serviceAccountName" . }}
rules:
  - apiGroups:
      - "captainhook.io"
    resources:
      - "hooks"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "captain-hook.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "captain-hook.serviceAccountName" . }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "captain-hook.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
